### ISSUE TITLE
Func: Copy Todo Object to Edit Form

### ISSUE THREAD

**Issue by hirooutdoor** [hirooutdoor/next-todo#11]
- [ ] Define the state for the edit form.
- [ ] Copy a specific todo object to the state for the edit form (include the id or index of the todo)
- [ ] Make sure that the value of the specific todo is displayed in the edit form.
