### ISSUE TITLE
Create Current Todo and change the edit click action

### ISSUE THREAD

**Issue by hirooutdoor** [hirooutdoor/next-todo#32]
Try to figure out
- [x] why all the todos are changed into input
- [x] what's happening then
- [x] how to make the conditional rendering work for the specific todo

**Comment by hirooutdoor** [comment]
#close this
